### ISSUE TITLE
Support custom props to the TextInput

### ISSUE THREAD

**Issue by yueshuaijie** [jaysoo/react-native-prompt#6]
There should be a way to customize more behaviour of text input, like keyboard type, whether password, max characters count, and so on.

We can introduce a new prop: textInputProps, which will apply to the text input.

**Comment by yueshuaijie** [comment]
I create a PR for this: #7 

Usage:
 `<Prompt textInputProps={{ keyboardType:'phone-pad' }} /> `

**Comment by sibelius** [comment]
@yueshuaijie @jaysoo u can close this, fixed on master
